[package]
name = "c_grammar"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
astray = "0.1.5"
hatch_result = "0.1.8"
logos = "0.13.0"
