[package]
name = "c_grammar"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "rsc"
path = "src/main.rs"

[dependencies]
astray = "0.*"
hatch_result = "0.*"
logos = "0.13.0"
nonempty = "0.8.1"
